### ISSUE TITLE
Documentation on env vars

### ISSUE THREAD

**Issue by zopyx** [heroku/salesforce-bulk#24]
Where is the documentation for the environment variables?

ajung@blackmoon2:~/src/ableton> bin/python bulk.py 
Traceback (most recent call last):
  File "bulk.py", line 3, in <module>
    client = get_client_bulk('test')
  File "/data/home/ajung/src/ableton/util.py", line 27, in get_client_bulk
    return SalesforceBulk(username=username, password=password + token)
  File "/data/home/ajung/src/ableton/lib/python2.7/site-packages/salesforce_bulk/salesforce_bulk.py", line 60, in **init**
    username, password)
  File "/data/home/ajung/src/ableton/lib/python2.7/site-packages/salesforce_bulk/salesforce_bulk.py", line 87, in login_to_salesforce
    ', '.join(missing_env_vars)))
RuntimeError: You must set SALESFORCE_CLIENT_ID, SALESFORCE_CLIENT_SECRET, SALESFORCE_REDIRECT_URI to use username/pass login

**Comment by ilyakamens** [comment]
+1

**Comment by lambacck** [comment]
Env Vars are no longer required as of the merge of #40
