### ISSUE TITLE
urlparse returning bad query errors, not able to login

### ISSUE THREAD

**Issue by Devarshi87** [heroku/salesforce-bulk#37]
i am passing the username and the password in the SalesforceBulk class but being block at this error 

> Traceback (most recent call last):
  File "D:\pydevWorkplace\SALESFORCEBIN\BinMiser\LoginModule.py", line 6, in <module>
    import salesforce_oauth_request
  File "C:\Python35\lib\site-packages\salesforce_oauth_request\__init__.py", line 4, in <module>
    from .utils import login, oauth_flow, token_login
  File "C:\Python35\lib\site-packages\salesforce_oauth_request\utils.py", line 9, in <module>
    import urlparse
  File "C:\Python35\lib\urlparse.py", line 418
    raise ValueError, "bad query field: %r" % (name_value,)
                    ^
SyntaxError: invalid syntax

don't know y this is happening. I am following the documentation.

**Comment by lambacck** [comment]
Fixed in #40
